---

- name: "Zsh | Install Zsh and Oh-My-Zsh on Ubuntu"
  ansible.builtin.package:
    name: zsh
    state: present

- name: Zsh | Check if path exists
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: omzsh_path_check

- name: Zsh | Install Oh-my-zsh
  ansible.builtin.shell:
    cmd: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  when: not omzsh_path_check.stat.exists

- name: Zsh | Clone Autosuggestions repo
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: Zsh | Clone syntax repo
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Zsh | Clone zsh-artisan repo
  ansible.builtin.git:
    repo: https://github.com/jessarcher/zsh-artisan.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/artisan"

- name: Zsh | Clone zsh-sail repo
  ansible.builtin.git:
    repo: https://github.com/ariaieboy/laravel-sail
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/laravel-sail"

- name: Zsh | Clone CD-LS repo
  ansible.builtin.git:
    repo: https://github.com/zshzoo/cd-ls
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/cd-ls"

# - name: "Zsh | Set Zsh as default shell on Ubuntu"
#   ansible.builtin.command:
#     cmd: "chsh -s /bin/zsh {{ host_user }}"
#   become: true

- name: "Zsh | Copy .zshrc"
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"


# - name: "zsh | Copy Private Files openai.apikey"
#   ansible.builtin.lineinfile:
#     name: "~/.openai.apikey"
#     line: "{{ OPENAI_KEY }}"
#     create: true
#     mode: "0600"
#     state: present

# - name: "zsh | Copy Private Files zshrc"
#   ansible.builtin.lineinfile:
#     name: "~/.zshrc"
#     line: "export OPENAI_API_KEY='{{ OPENAI_API_KEY }}'"
#     create: true
#     mode: "0600"
#     state: present

- name: "zsh | Copy Git Prune Script to {{ ansible_user_dir }}/local/bin"
  ansible.builtin.copy:
    src: "gprune.sh"
    dest: "{{ ansible_user_dir }}/.local/bin/gprune"
    mode: "0755"

- name: Install starship prompt
  homebrew:
    name: starship
    state: present

- name: Ensure starship config directory exists
  file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: '0755'

- name: Copy default starship.toml
  copy:
    src: starship.toml
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    mode: '0644'
    force: no
