---
- name: Run Mac Tasks
  ansible.builtin.import_tasks: mac.yml
  when: ansible_system == 'Darwin'

- name: Run WSL Tasks
  ansible.builtin.import_tasks: wsl.yml
  when: ansible_host_environment_is_wsl

- name: Run Ubuntu Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when:
    - ansible_os_family == 'Debian'
    - not ansible_host_environment_is_wsl
