---
- name: "Tailscale | Update APT cache"
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: "Tailscale | Install dependencies"
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
    state: present
  become: true

- name: "Tailscale | Add Tailscale's official GPG key"
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.gpg
    keyring: /etc/apt/keyrings/tailscale.gpg
    state: present
  become: true

- name: "Tailscale | Add Tailscale's stable repository"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu {{ ansible_distribution_release }} main"
    state: present
  become: true

- name: "Tailscale | Install Tailscale"
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true
  become: true

- name: "Tailscale | Enable and start Tailscale service"
  ansible.builtin.systemd:
    name: tailscaled
    enabled: true
    state: started
  become: true
