---
- name: Install Ghostty on macOS
  community.general.homebrew_cask:
    name: ghostty
    state: latest
  ignore_errors: true

- name: Ensure Ghostty config directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/ghostty"
    state: directory

- name: Copy Ghostty config
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"
