---
- name: Run Mac Tasks
  ansible.builtin.import_tasks: mac.yml
  when: ansible_os_family == 'Darwin'

- name: Run Ubuntu/WSL Tasks
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian'
